levels = [
    [
        'XXXXXXXXXXXXX  X',
        'XXXXXXX        X',
        'XXXX           X',
        'XXX          XXX',
        'XXX         XXXX',
        'XXX           XX',
        'XXXXX    $     X',
        'XX             X',
        'X              X',  # 0
        'X            XXX',
        '              XX',
        '       XX     XX',
        ' P XX  XX  ^^^XX',
        'XXXXX  XX^^XXXXX',
        'XXXXX^^XXXXXXXXX',
        'XXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX   X',
        'XXXXXX    XX   X',
        'XXXX    $ XX   X',
        'XXX       XX   X',
        'XXX       X    X',
        'XXX    ^  X    X',
        'X      X      XX',
        'XXXX   X      XX',  # 1
        'XXXX   X      XX',
        'XXXX   X      XX',
        'XXXX   X     XXX',
        'XXXX   X       X',
        '  XX   X       X',
        '   X   X^^^     ',
        ' P     XXXX     ',
        'XXXXXXXXXXX     ',
    ],
    [
        'XXXXXXXX    XXXX',
        'XXXXXX       XXX',
        'XXXXXX       XXX',
        'XXXXX         XX',
        'X XXX          X',
        '   XXXX         ',
        ' $  XXX^^^^     ',
        '    XXXXXXX     ',
        '        XX    XX',  # 2
        '              XX',
        '              XX',
        '       ^^^^   XX',
        '       XXXX   XX',
        ' P      XX    XX',
        'XXX  S  XX   SXX',
        'XXX  X  XX   XXX',
    ],
    [
        'XXXXX   XXXXXXXX',
        '                ',
        '                ',
        '  $  XXX        ',
        '     XXXX       ',
        '      XX        ',
        '      XX    HH  ',
        '      XX        ',
        '      XX        ',  # 3
        '      XX   HH   ',
        '      XX        ',
        '      XX      HH',
        ' P              ',
        'XXXX        HH  ',
        'XXXX    HH      ',
        'XXXXHH          ',
    ],
    [
        'XX   XXXXXXXXXXX',
        '     X        XX',
        '               X',
        '   XXX         X',
        '          ^^   X',
        '          XX    ',
        '      ^^  XX    ',
        '      XX  XX    ',
        '      X   XXX   ',  # 4
        '      X    XX   ',
        '      X         ',
        ' P    X         ',
        'XXXX  X         ',
        '  X   X    XXXXX',
        '  X   X$    X   ',
        '  X   X     X   ',
    ],
    [
        'XXXXXXXXXXXX  XX',
        'XXXXXXXXXXXX  XX',
        'XXXXXXXXXXXX  XX',
        'XXXXXXXXXXXX  XX',
        'XXXXX XXX     XX',
        '  XXX         XX',
        '  VVV        XXX',
        '             XXX',
        '         O      ',  # 5
        '                ',
        '                ',
        ' P              ',
        'XXX             ',
        'XXXXXXX       XX',
        'XXXXXXX   XXXXXX',
        'XXXXXXX   XXXXXX',
    ],
    [
        'X   XXXXXXXXXXXX',
        'X   XXXXXXXXXXXX',
        'X      O    XXXX',
        'X     ^^^    XXX',
        'X    ^XXX    XXX',
        'X^^^^XXXX  <XXXX',
        'XXXXXXXXX  <XXXX',
        'XXXXXX     <XXXX',
        'XXXXXX O   <XXXX',  # 6
        'XXXXXX   ^^^XXXX',
        'XXXXXX  <XXXXXXX',
        'XXXXXX  <XXXXXXX',
        '        <XXXXXXX',
        '        <XXXXXXX',
        ' P      <XXXXXXX',
        'XXXX    <XXXXXXX',
    ],
    [
        'X    XXXXXXXXXXX',
        'X        XXXXXXX',
        'X             XX',
        'X             XX',
        'X     O       XX',
        'X^            XX',
        'XX            XX',
        'XX            H ',
        'X             H ',  # 7
        '                ',
        '                ',
        '                ',
        '            S   ',
        '            X   ',
        ' P    HHH       ',
        'XXXX            ',
    ],
    [
        'XXX   XXXXXXXXXX',
        'X     XXX     XX',
        'X     XXX     XX',
        '              XX',
        '    O   O     XX',
        '              XX',
        '              XX',
        '                ',
        '                ',  # 8
        '                ',
        '                ',
        '                ',
        '  P   ^^^       ',
        '^^X^^^XXX   SS  ',
        'XXXXXXXXX^^^XX^^',
        'XXXXXXXXXXXXXXXX',
    ],
    [
        'XXX    XXXXXXXXX',
        'XXX    XX    XXX',
        'XXX    X       X',
        'XXX    X        ',
        'XXXX   X        ',
        'XXXX            ',
        'XXXX         X  ',
        'XXXX^^      ^X  ',  # 9
        '   XXX      XX  ',
        '             X  ',
        '                ',
        '                ',
        '                ',
        ' P              ',
        ' X   HH   HH    ',
        ' X              ',
    ],
    [
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '       F        ',
        '       XX       ',  # 10
        '      XXXX      ',
        '     XXXXXX     ',
        '     XXXXXX     ',
        '     XXXXXX     ',
        '     XXXXXXX    ',
        '  XXXXXXXXXX    ',
        'P XXXXXXXXXXX   ',
        'XXXXXXXXXXXXXXXX',
    ],
    [
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',  # 11
        '                ',
        '} } }  } } } } }',
        '                ',
        '        {       ',
        '                ',
        ' P  }       }   ',
        'XXXXXXXXXXXXXXXX',
    ]
]
