levels = [
    [
        'XXXXXXXXXXXXX  X',
        'XXXXXXX        X',
        'XXXX           X',
        'XXX          XXX',
        'XXX         XXXX',
        'XXX           XX',
        'XXXXX    $     X',
        'XX             X',
        'X              X',
        'X            XXX',
        '              XX',
        '       XX     XX',
        ' P XX  XX  ^^^XX',
        'XXXXX  XX^^XXXXX',
        'XXXXX^^XXXXXXXXX',
        'XXXXXXXXXXXXXXXX',
    ],
    [
        '                ',
        '                ',
        '             O  ',
        '                ',
        '                ',
        '                ',
        '          XX    ',
        '          XX    ',
        '   $      XX    ',
        '        X       ',
        '        X       ',
        '        X       ',
        '      X         ',
        '      X         ',
        '  P   X         ',
        'XXXXXXXXXXXX  XX',
    ],
    [
        'XXXXXX    XXXXXX',
        '           O    ',
        '                ',
        '                ',
        '                ',
        '         S      ',
        '         X      ',
        '             O  ',
        '                ',
        '                ',
        '           F    ',
        '     ^^  XXXXXXX',
        '     XX         ',
        '     XX      $  ',
        ' P   XX         ',
        'XXXXXXXXXXXXXXXX',
    ]
]
